# Generated by Django 3.0 on 2021-11-08 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddMode', models.BooleanField(default=False, verbose_name=' _Add Mode')),
                ('EdirMode', models.BooleanField(default=False, verbose_name=' _Edit Mode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserMode',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShowGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.CharField(blank=True, default='NoData', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ShowGroup',
                'managed': True,
            },
        ),
    ]
