# Generated by Django 3.0 on 2021-11-09 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0002_showgroup_usermode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermode',
            old_name='EdirMode',
            new_name='EditMode',
        ),
    ]
