# Generated by Django 3.0 on 2021-11-09 00:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersettings', '0003_auto_20211109_0017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMode',
            new_name='UserModes',
        ),
    ]
