# Generated by Django 3.0 on 2021-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0004_auto_20211109_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='AddMode',
            field=models.BooleanField(default=False, verbose_name=' _Add Mode'),
        ),
        migrations.AddField(
            model_name='show',
            name='EditMode',
            field=models.BooleanField(default=False, verbose_name=' _Edit Mode'),
        ),
    ]
