# Generated by Django 3.0 on 2021-11-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0005_auto_20211109_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='AddMode',
            new_name='ShowAddMode',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='EditMode',
            new_name='ShowEditMode',
        ),
    ]
