# Generated by Django 3.0 on 2021-11-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0006_auto_20211109_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='ShowAddMode',
            new_name='AddMode',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='ShowEditMode',
            new_name='EditMode',
        ),
    ]
