# Generated by Django 3.0 on 2021-11-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0009_showgroup_groupcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showgroup',
            name='Group',
            field=models.CharField(blank=True, default='NoData', max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='showgroup',
            name='GroupCheck',
            field=models.BooleanField(default=False, verbose_name=' _Incude/Exclude'),
        ),
    ]
