# Generated by Django 3.0 on 2021-10-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarfungi',
            name='SimilarFungiId',
            field=models.IntegerField(default=1),
        ),
    ]
