# Generated by Django 3.0 on 2021-10-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0005_similarfungi_similarfungiid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarfungi',
            name='SimilarFungiId',
        ),
    ]
