# Generated by Django 3.0 on 2021-10-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0006_remove_similarfungi_similarfungiid'),
    ]

    operations = [
        migrations.AddField(
            model_name='similarfungi',
            name='SimilarFungiId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
