# Generated by Django 3.0 on 2021-10-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0007_similarfungi_similarfungiid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netlinks',
            options={'managed': True, 'ordering': ['Fungi'], 'verbose_name': 'NetLinks', 'verbose_name_plural': 'NetLinks'},
        ),
        migrations.RemoveField(
            model_name='classification',
            name='Source',
        ),
    ]
