# Generated by Django 3.0 on 2021-10-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0008_auto_20211013_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'managed': True, 'ordering': ['Fungi'], 'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
        migrations.AlterField(
            model_name='fungicomments',
            name='Comments',
            field=models.CharField(blank=True, default='no comments', max_length=5000, null=True),
        ),
    ]
