# Generated by Django 3.0 on 2021-11-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0010_auto_20211108_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitingbody',
            name='DataPresent',
        ),
        migrations.AlterField(
            model_name='netlinks',
            name='Website',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='netlinks',
            name='Websiteurl',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True, verbose_name='URL'),
        ),
    ]
