# Generated by Django 3.0 on 2021-11-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0011_auto_20211117_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term', models.CharField(blank=True, default='NoData', max_length=255, null=True)),
                ('Meaning', models.CharField(blank=True, default='NoData', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Glossary',
                'verbose_name_plural': 'Glossary',
                'db_table': 'Glossary',
                'ordering': ['Term'],
                'managed': True,
            },
        ),
    ]
