# Generated by Django 3.0 on 2021-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0012_glossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
