# Generated by Django 3.0 on 2021-11-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0013_glossary_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='Source',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='Term',
            field=models.CharField(blank=True, default='NoData', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='similarfungi',
            name='SimilarFungiId',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Similar Fungi id'),
        ),
        migrations.AlterField(
            model_name='similarfungi',
            name='SimilarFungiName',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True, verbose_name='Similar Fungi Name'),
        ),
    ]
