# Generated by Django 3.0 on 2021-12-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0014_auto_20211126_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='term_lower_case',
            field=models.CharField(blank=True, default='NoData', max_length=50, null=True),
        ),
    ]
