# Generated by Django 3.0 on 2021-12-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0015_glossary_term_lower_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='term_lower_case',
            field=models.CharField(blank=True, default='NoData', max_length=50, null=True, verbose_name='term lc'),
        ),
    ]
