# Generated by Django 3.0 on 2021-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0016_auto_20211212_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungi',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
