# Generated by Django 3.0 on 2021-12-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0017_fungi_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fungi',
            name='slug',
        ),
    ]
