# Generated by Django 3.0 on 2021-12-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0020_fungicomments_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='flesh',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='fruitingbody',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='gills',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='habitat',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='latinsynonyms',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='othercommonnames',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='poresandtubes',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='seasons',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='similarfungi',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='spores',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='stipe',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
