# Generated by Django 3.0 on 2021-12-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0024_auto_20211216_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsources',
            name='Detail',
            field=models.CharField(blank=True, choices=[('Habitat', 'Habitat'), ('Fruiting Body', 'FruitingBody'), ('Stipe', 'Stipe'), ('Cuisine', 'Cuisine'), ('Flesh', 'Flesh'), ('Similar Fungi', 'Similar Fungi'), ('Common Names', 'Common Names'), ('Latin Synomyms', 'Latin Synomyms'), ('Spore', 'Spore'), ('Seasons', 'Seasons'), ('Status', 'Status'), ('Pores And Tubes', 'PoresAndTubes'), ('Gills', 'Gills'), ('Comments', 'Comments'), ('Classification', 'Classification')], default='NoData', max_length=255, null=True),
        ),
    ]
