# Generated by Django 3.0 on 2022-06-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0025_auto_20211216_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fungicomments',
            options={'managed': True, 'ordering': ['Fungi'], 'verbose_name': 'FungiComments', 'verbose_name_plural': 'FungiComments'},
        ),
        migrations.AlterField(
            model_name='detailsources',
            name='Detail',
            field=models.CharField(blank=True, choices=[('Habitat', 'Habitat'), ('FruitingBody', 'FruitingBody'), ('Stipe', 'Stipe'), ('Cuisine', 'Cuisine'), ('Flesh', 'Flesh'), ('SimilarFungi', 'SimilarFungi'), ('OtherCommonNames', 'OtherCommonNames'), ('LatinSynonyms', 'LatinSynonyms'), ('Spores', 'Spores'), ('Seasons', 'Seasons'), ('Status', 'Status'), ('PoresAndTubes', 'PoresAndTubes'), ('Gills', 'Gills'), ('Comments', 'Comments'), ('Classification', 'Classification')], default='NoData', max_length=255, null=True),
        ),
    ]
