# Generated by Django 3.0 on 2022-07-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0026_auto_20220622_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='latinsynonyms',
            name='LatinSynonymSource',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='fungi',
            name='Macromycetes',
            field=models.CharField(blank=True, choices=[('initial', ''), ('Yes', 'Yes'), ('No', 'No')], default='NoData', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fungi',
            name='UKSpecies',
            field=models.CharField(blank=True, choices=[('initial', ''), ('Yes', 'Yes'), ('No', 'No')], default='NoData', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poresandtubes',
            name='Milk',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stipe',
            name='Ring',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='NoData', max_length=20, null=True),
        ),
    ]
