# Generated by Django 3.0 on 2022-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0029_auto_20220818_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitingbody',
            name='Shape',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
    ]
