# Generated by Django 3.0 on 2022-08-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0030_fruitingbody_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitingbody',
            name='ShapeDescription',
        ),
        migrations.AddField(
            model_name='stipe',
            name='Shape',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True),
        ),
    ]
