# Generated by Django 3.0 on 2022-08-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0031_auto_20220818_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitingbody',
            name='RimDescription',
        ),
    ]
