# Generated by Django 3.0 on 2022-08-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0032_remove_fruitingbody_rimdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitingbody',
            name='CapTextureDescription',
        ),
    ]
