# Generated by Django 3.0 on 2022-08-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0034_auto_20220819_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fungi',
            name='BMSList',
        ),
        migrations.RemoveField(
            model_name='fungi',
            name='NBNList',
        ),
    ]
