# Generated by Django 3.0 on 2022-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0035_auto_20220830_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fungi',
            name='UKSpecies',
        ),
        migrations.AlterField(
            model_name='fungi',
            name='Macromycetes',
            field=models.CharField(blank=True, choices=[('initial', ''), ('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=8, null=True),
        ),
    ]
