# Generated by Django 3.0 on 2022-09-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0037_auto_20220905_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='RecordedInUK',
        ),
        migrations.RemoveField(
            model_name='status',
            name='UKOccurences',
        ),
        migrations.AlterField(
            model_name='fungi',
            name='UKSpecies',
            field=models.CharField(blank=True, choices=[('initial', ''), ('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True, verbose_name='Recorded in UK'),
        ),
    ]
