# Generated by Django 3.0 on 2022-09-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fungi', '0038_auto_20220906_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungi',
            name='Macromycetes',
            field=models.CharField(blank=True, choices=[('NoData', 'NoData'), ('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='fungi',
            name='UKSpecies',
            field=models.CharField(blank=True, choices=[('NoData', 'NoData'), ('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True, verbose_name='Recorded in UK'),
        ),
        migrations.AlterField(
            model_name='gills',
            name='GillsPresent',
            field=models.CharField(blank=True, choices=[('NoData', 'NoData'), ('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gills',
            name='Milk',
            field=models.CharField(blank=True, choices=[('NoData', 'NoData'), ('Yes', 'Yes'), ('No', 'No')], default='NoData', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poresandtubes',
            name='Milk',
            field=models.CharField(blank=True, choices=[('NoData', 'NoData'), ('Yes', 'Yes'), ('No', 'No')], default='NoData', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poresandtubes',
            name='PoresPresent',
            field=models.CharField(blank=True, choices=[('NoData', 'NoData'), ('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='StatusComments',
            field=models.CharField(blank=True, default='no comments', max_length=2048, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='status',
            name='StatusData',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='WhereFound',
            field=models.CharField(blank=True, default='NoData', max_length=255, null=True, verbose_name='Where found'),
        ),
        migrations.AlterField(
            model_name='stipe',
            name='Ring',
            field=models.CharField(blank=True, choices=[('NoData', 'NoData'), ('Yes', 'Yes'), ('No', 'No')], default='NoData', max_length=20, null=True),
        ),
    ]
